SELECT
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_number' ->> 'df_value')::text AS sample_number,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'date_of_sample_collection' ->> 'df_value')::text AS date_of_sample_collection,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'time_of_sample_collection' ->> 'df_value')::text AS time_of_sample_collection,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'reason_for_sampling' ->> 'df_value')::text AS reason_for_sampling,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'reason_for_sampling_other' ->> 'df_value')::text AS reason_for_sampling_other,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'source_of_sample' ->> 'df_value')::text AS source_of_sample,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_supected_of_causing_illness' ->> 'df_value')::text AS sample_supected_of_causing_illness,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_source_has_pump' ->> 'df_value')::text AS sample_source_has_pump,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_source_pump_usage_duration' ->> 'df_value')::text AS sample_source_pump_usage_duration,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_source_pump_overhaul' ->> 'df_value')::text AS sample_source_pump_overhaul,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_is_repeat' ->> 'df_value')::text AS sample_is_repeat,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'previous_sample_status' ->> 'df_value')::text AS previous_sample_status,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'rejected_sample_tracking_number' ->> 'df_value')::text AS rejected_sample_tracking_number,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sources_of_pollution_exist' ->> 'df_value')::text AS sources_of_pollution_exist,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'type_of_pollution' ->> 'df_value')::text AS type_of_pollution,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'description_of_pollution' ->> 'df_value')::text AS description_of_pollution,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'water_sample_source_is_treated' ->> 'df_value')::text AS water_sample_source_is_treated,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'water_sample_source_method_of_treatment' ->> 'df_value')::text AS water_sample_source_method_of_treatment,
    (doc -> 'DForms' -> 'sample_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'water_sample_source_date_of_treatment' ->> 'df_value')::text AS water_sample_source_date_of_treatment,
    (doc -> 'DForms' -> 'collector_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_collector_name' ->> 'df_value')::text AS sample_collector_name,
    (doc -> 'DForms' -> 'collector_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'sample_collector_designation' ->> 'df_value')::text AS sample_collector_designation,
    (doc -> 'DForms' -> 'collector_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'collector_phone_number' ->> 'df_value')::text AS collector_phone_number,
    (doc -> 'DForms' -> 'collector_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'collectors_email_address' ->> 'df_value')::text AS collectors_email_address,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'date_of_sample_reception' ->> 'df_value')::text AS date_of_sample_reception,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'date_of_sample_examination' ->> 'df_value')::text AS date_of_sample_examination,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'presumptive_coli_test' ->> 'df_value')::text AS presumptive_coli_test,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'escherichia_coli' ->> 'df_value')::text AS escherichia_coli,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'specialist_bacteriologist' ->> 'df_value')::text AS specialist_bacteriologist,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'compiled_by' ->> 'df_value')::text AS compiled_by,
    (doc -> 'DForms' -> 'laboratory_information_water_sampling' -> 0 -> 'DFields' -> 'values' -> 'reviewed_by' ->> 'df_value')::text AS reviewed_by,
    (doc -> 'DFields' -> 'values' -> 'title_site_information' ->> 'df_value')::text AS title_site_information,
    (doc -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DFields' -> 'values' -> 'ward' ->> 'df_value')::text AS ward,
    (doc -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DFields' -> 'values' -> 'sample_collection_pickup_site' ->> 'df_value')::text AS sample_collection_pickup_site
FROM {{ source('couchdb', 'couchdb') }}
WHERE
    (doc ->> 'type')::text = 'dform'
AND
    (doc -> 'DForms' -> 'sample_information_water_sampling') IS NOT NULL
AND
    (doc -> 'ident') IS NOT NULL
