SELECT
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DFields' -> 'values' -> 'syndrome' ->> 'df_value')::text AS syndrome,
    (doc -> 'DFields' -> 'values' -> 'disease' ->> 'df_value')::text AS disease,
    (doc -> 'DFields' -> 'values' -> 'EPID' ->> 'df_value')::text AS epid,
    (doc -> 'DFields' -> 'values' -> 'date_of_investigation' ->> 'df_value')::text AS date_of_investigation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'given' ->> 'df_value')::text AS given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'sex' ->> 'df_value')::text AS sex,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'date_of_birth' ->> 'df_value')::text AS date_of_birth,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_years' ->> 'df_value')::text AS age_years,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_months' ->> 'df_value')::text AS age_months,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation' ->> 'df_value')::text AS occupation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation_other' ->> 'df_value')::text AS occupation_other,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'country' ->> 'df_value')::text AS country,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'town_village_camp' ->> 'df_value')::text AS town_village_camp,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_residence' ->> 'df_value')::text AS title_residence,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_parent_guardian' ->> 'df_value')::text AS title_parent_guardian,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_family_name' ->> 'df_value')::text AS guardian_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_given_name' ->> 'df_value')::text AS guardian_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_phone_number' ->> 'df_value')::text AS guardian_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_respondent' ->> 'df_value')::text AS title_respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_family_name' ->> 'df_value')::text AS respondent_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_given_name' ->> 'df_value')::text AS respondent_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_address' ->> 'df_value')::text AS respondent_address,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_phone_number' ->> 'df_value')::text AS respondent_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_relationship' ->> 'df_value')::text AS respondent_relationship,
    (doc -> 'DForms' -> 'reporting_location' -> 0 -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS reporting_county,
    (doc -> 'DForms' -> 'reporting_location' -> 0 -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS reporting_subcounty,
    (doc -> 'DForms' -> 'reporting_location' -> 0 -> 'DFields' -> 'values' -> 'health_facility' ->> 'df_value')::text AS reporting_health_facility,
    (doc -> 'DForms' -> 'vaccination_meningitis' -> 0 -> 'DFields' -> 'values' -> 'vaccine' ->> 'df_value')::text AS vaccine,
    (doc -> 'DForms' -> 'vaccination_meningitis' -> 0 -> 'DFields' -> 'values' -> 'vaccine_doses' ->> 'df_value')::text AS vaccine_doses,
    (doc -> 'DForms' -> 'vaccination_meningitis' -> 0 -> 'DFields' -> 'values' -> 'vaccine_last_dose_date' ->> 'df_value')::text AS vaccine_last_dose_date,
    (doc -> 'DForms' -> 'vaccination_meningitis' -> 0 -> 'DFields' -> 'values' -> 'vaccine_information_source' ->> 'df_value')::text AS vaccine_information_source,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'lumbar_puncture_date' ->> 'df_value')::text AS lumbar_puncture_date,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'lumbar_puncture_time' ->> 'df_value')::text AS lumbar_puncture_time,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'celebrospinal_fluid_appearance' ->> 'df_value')::text AS celebrospinal_fluid_appearance,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'inoculation_date' ->> 'df_value')::text AS inoculation_date,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'inoculation_time' ->> 'df_value')::text AS inoculation_time,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'sample_transport_medium' ->> 'df_value')::text AS sample_transport_medium,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'sample_transport_medium_others' ->> 'df_value')::text AS sample_transport_medium_others,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'laboratory_test_requested' ->> 'df_value')::text AS laboratory_test_requested,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'reference_laboratory' ->> 'df_value')::text AS reference_laboratory,
    (doc -> 'DForms' -> 'laboratory_sample_meningitis' -> 0 -> 'DFields' -> 'values' -> 'patient_on_treatment' ->> 'df_value')::text AS patient_on_treatment,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'symptoms' ->> 'df_value')::text AS symptoms,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'date_of_onset' ->> 'df_value')::text AS date_of_onset,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'health_facility' ->> 'df_value')::text AS clinical_health_facility,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'date_first_seen_at_facility' ->> 'df_value')::text AS date_first_seen_at_facility,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'admission_date' ->> 'df_value')::text AS admission_date,
    (doc -> 'DForms' -> 'clinical_information_meningitis' -> 0 -> 'DFields' -> 'values' -> 'patient_status' ->> 'df_value')::text AS patient_status
FROM {{ source('couchdb', 'couchdb') }}
WHERE 
    (doc ->> 'type') = 'dform'
    AND (((doc -> 'DFields' -> 'values') -> 'disease' ->> 'df_value') = 'Meningitis')
    AND (doc ->> 'ident') IS NOT NULL
