SELECT
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'sources_of_water' ->> 'df_value')::text AS sources_of_water,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'sources_of_water_other' ->> 'df_value')::text AS sources_of_water_other,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'water_source_is_protected' ->> 'df_value')::text AS water_source_is_protected,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'water_source_is_treated' ->> 'df_value')::text AS water_source_is_treated,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'water_source_method_of_treatment' ->> 'df_value')::text AS water_source_method_of_treatment,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'water_source_method_of_treatment_other' ->> 'df_value')::text AS water_source_method_of_treatment_other,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'distance_of_water_source_from_household' ->> 'df_value')::text AS distance_of_water_source_from_household,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'amount_of_water_consumed' ->> 'df_value')::text AS amount_of_water_consumed,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'type_of_water_storage_container' ->> 'df_value')::text AS type_of_water_storage_container,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'type_of_water_storage_container_other' ->> 'df_value')::text AS type_of_water_storage_container_other,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'dedicated_storage_container_for_drinking_water' ->> 'df_value')::text AS dedicated_storage_container_for_drinking_water,
    (doc -> 'DForms' -> 'water_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'water_storage_is_covered' ->> 'df_value')::text AS water_storage_is_covered,
    (doc -> 'DForms' -> 'collector_information' -> 0 -> 'DFields' -> 'values' -> 'sample_collector_name' ->> 'df_value')::text AS sample_collector_name,
    (doc -> 'DForms' -> 'collector_information' -> 0 -> 'DFields' -> 'values' -> 'sample_collector_designation' ->> 'df_value')::text AS sample_collector_designation,
    (doc -> 'DForms' -> 'collector_information' -> 0 -> 'DFields' -> 'values' -> 'collector_phone_number' ->> 'df_value')::text AS collector_phone_number,
    (doc -> 'DForms' -> 'collector_information' -> 0 -> 'DFields' -> 'values' -> 'collectors_email_address' ->> 'df_value')::text AS collectors_email_address,
    (doc -> 'DForms' -> 'hygiene_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'handwashing_facility_exists' ->> 'df_value')::text AS handwashing_facility_exists,
    (doc -> 'DForms' -> 'hygiene_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'handwashing_facility_has_water_and_soap' ->> 'df_value')::text AS handwashing_facility_has_water_and_soap,
    (doc -> 'DForms' -> 'hygiene_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'handwashing_facility_near_water_source' ->> 'df_value')::text AS handwashing_facility_near_water_source,
    (doc -> 'DForms' -> 'sanitation_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'household_sanitation_facilities' ->> 'df_value')::text AS household_sanitation_facilities,
    (doc -> 'DForms' -> 'sanitation_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'household_sanitation_facilities_other' ->> 'df_value')::text AS household_sanitation_facilities_other,
    (doc -> 'DForms' -> 'sanitation_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'household_sanitation_method_in_use' ->> 'df_value')::text AS household_sanitation_method_in_use,
    (doc -> 'DForms' -> 'sanitation_information_rwa' -> 0 -> 'DFields' -> 'values' -> 'distance_of_sanitation_facility_from_water_source' ->> 'df_value')::text AS distance_of_sanitation_facility_from_water_source,
    (doc -> 'DForms' -> 'water_disposal_information' -> 0 -> 'DFields' -> 'values' -> 'stagnant_water_exists' ->> 'df_value')::text AS stagnant_water_exists,
    (doc -> 'DForms' -> 'water_disposal_information' -> 0 -> 'DFields' -> 'values' -> 'sources_of_stagnant_water' ->> 'df_value')::text AS sources_of_stagnant_water,
    (doc -> 'DForms' -> 'water_disposal_information' -> 0 -> 'DFields' -> 'values' -> 'challenges_due_to_stagnant_water' ->> 'df_value')::text AS challenges_due_to_stagnant_water,
    (doc -> 'DForms' -> 'water_disposal_information' -> 0 -> 'DFields' -> 'values' -> 'challenges_due_to_stagnant_water_other' ->> 'df_value')::text AS challenges_due_to_stagnant_water_other,
    (doc -> 'DForms' -> 'water_disposal_information' -> 0 -> 'DFields' -> 'values' -> 'drainage_slope_exists' ->> 'df_value')::text AS drainage_slope_exists,
    (doc -> 'DForms' -> 'solid_waste_management_information' -> 0 -> 'DFields' -> 'values' -> 'method_of_solid_waste_disposal' ->> 'df_value')::text AS method_of_solid_waste_disposal,
    (doc -> 'DForms' -> 'solid_waste_management_information' -> 0 -> 'DFields' -> 'values' -> 'method_of_solid_waste_disposal_other' ->> 'df_value')::text AS method_of_solid_waste_disposal_other,
    (doc -> 'DFields' -> 'values' -> 'title_site_information' ->> 'df_value')::text AS title_site_information,
    (doc -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DFields' -> 'values' -> 'ward' ->> 'df_value')::text AS ward,
    (doc -> 'DFields' -> 'values' -> 'town_village_camp' ->> 'df_value')::text AS town_village_camp,
    (doc -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DFields' -> 'values' -> 'title_head_of_household' ->> 'df_value')::text AS title_head_of_household,
    (doc -> 'DFields' -> 'values' -> 'name_of_head_of_household' ->> 'df_value')::text AS name_of_head_of_household,
    (doc -> 'DFields' -> 'values' -> 'phone_number_of_head_of_household' ->> 'df_value')::text AS phone_number_of_head_of_household,
    (doc -> 'DFields' -> 'values' -> 'email_of_head_of_household' ->> 'df_value')::text AS email_of_head_of_household,
    (doc -> 'DFields' -> 'values' -> 'title_population' ->> 'df_value')::text AS title_population,
    (doc -> 'DFields' -> 'values' -> 'population_of_household_under_five_years' ->> 'df_value')::text AS population_of_household_under_five_years
FROM {{ source('couchdb', 'couchdb') }}
WHERE
    (doc ->> 'type')::text = 'dform'
AND
    (doc -> 'DForms' -> 'water_information_rwa') IS NOT NULL
AND
    (doc -> 'ident') IS NOT NULL
