SELECT 
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DFields' -> 'values' -> 'syndrome' ->> 'df_value')::text AS syndrome,
    (doc -> 'DFields' -> 'values' -> 'disease' ->> 'df_value')::text AS disease,
    (doc -> 'DFields' -> 'values' -> 'EPID' ->> 'df_value')::text AS epid,
    (doc -> 'DFields' -> 'values' -> 'date_of_investigation' ->> 'df_value')::text AS date_of_investigation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'given' ->> 'df_value')::text AS given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'sex' ->> 'df_value')::text AS sex,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'date_of_birth' ->> 'df_value')::text AS date_of_birth,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_years' ->> 'df_value')::text AS age_years,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_months' ->> 'df_value')::text AS age_months,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation' ->> 'df_value')::text AS occupation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation_other' ->> 'df_value')::text AS occupation_other,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'country' ->> 'df_value')::text AS country,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'town_village_camp' ->> 'df_value')::text AS town_village_camp,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_residence' ->> 'df_value')::text AS title_residence,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_parent_guardian' ->> 'df_value')::text AS title_parent_guardian,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_family_name' ->> 'df_value')::text AS guardian_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_given_name' ->> 'df_value')::text AS guardian_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_phone_number' ->> 'df_value')::text AS guardian_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_respondent' ->> 'df_value')::text AS title_respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_family_name' ->> 'df_value')::text AS respondent_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_given_name' ->> 'df_value')::text AS respondent_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_address' ->> 'df_value')::text AS respondent_address,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_phone_number' ->> 'df_value')::text AS respondent_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_relationship' ->> 'df_value')::text AS respondent_relationship,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'exposure_type_rabies' ->> 'df_value')::text AS exposure_type_rabies,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'exposure_date' ->> 'df_value')::text AS exposure_date,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'exposure_rabies_injury' ->> 'df_value')::text AS exposure_rabies_injury,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'exposure_rabies_injury_site' ->> 'df_value')::text AS exposure_rabies_injury_site,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_species' ->> 'df_value')::text AS animal_species,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_species_other' ->> 'df_value')::text AS animal_species_other,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_vaccinated' ->> 'df_value')::text AS animal_vaccinated,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_rabies_suspect' ->> 'df_value')::text AS animal_rabies_suspect,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_observed' ->> 'df_value')::text AS animal_observed,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_dead' ->> 'df_value')::text AS animal_dead,
    (doc -> 'DForms' -> 'case_exposure_rabies' -> 0 -> 'DFields' -> 'values' -> 'animal_dead_days' ->> 'df_value')::text AS animal_dead_days,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS repondent,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS repondent_family_name,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'given_name' ->> 'df_value')::text AS repondent_given_name,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS repondent_phone_number,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'address' ->> 'df_value')::text AS repondent_address,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'relationship' ->> 'df_value')::text AS repondent_relationship,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'relationship_other' ->> 'df_value')::text AS repondent_relationship_other,
    (doc -> 'DForms' -> 'case_vaccination' -> 0 -> 'DFields' -> 'values' -> 'vaccinated' ->> 'df_value')::text AS vaccinated,
    (doc -> 'DForms' -> 'case_vaccination' -> 0 -> 'DFields' -> 'values' -> 'vaccine_name' ->> 'df_value')::text AS vaccine_name,
    (doc -> 'DForms' -> 'case_vaccination' -> 0 -> 'DFields' -> 'values' -> 'vaccine_doses' ->> 'df_value')::text AS vaccine_doses,
    (doc -> 'DForms' -> 'case_vaccination' -> 0 -> 'DFields' -> 'values' -> 'health_facility' ->> 'df_value')::text AS health_facility,
    (doc -> 'DForms' -> 'case_vaccination' -> 0 -> 'DFields' -> 'values' -> 'vaccination_date' ->> 'df_value')::text AS vaccination_date,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'case_seen_at_facility' ->> 'df_value')::text AS case_seen_at_facility,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'date_first_seen_at_facility' ->> 'df_value')::text AS date_first_seen_at_facility,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'admitted' ->> 'df_value')::text AS admitted,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'health_facility_name' ->> 'df_value')::text AS health_facility_name,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'admission_date' ->> 'df_value')::text AS admission_date,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'inpatient_number' ->> 'df_value')::text AS inpatient_number,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'discharge_date' ->> 'df_value')::text AS discharge_date,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'patient_status' ->> 'df_value')::text AS patient_status,
    doc
FROM {{ source('couchdb', 'couchdb') }}
WHERE 
  (doc ->> 'type'::text) = 'dform'::text 
  AND ((((doc -> 'DFields'::text) -> 'values'::text) -> 'disease'::text) ->> 'df_value'::text) = 'Rabies'::text 
  AND (doc -> 'ident'::text) IS NOT NULL
