SELECT 
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DFields' -> 'values' -> 'syndrome' ->> 'df_value')::text AS syndrome,
    (doc -> 'DFields' -> 'values' -> 'disease' ->> 'df_value')::text AS disease,
    (doc -> 'DFields' -> 'values' -> 'EPID' ->> 'df_value')::text AS epid,
    (doc -> 'DFields' -> 'values' -> 'date_of_investigation' ->> 'df_value')::text AS date_of_investigation,
    (doc -> 'DFields' -> 'values' -> 'location_of_investigation' ->> 'df_value')::text AS location_of_investigation,
    (doc -> 'DFields' -> 'values' -> 'type_of_case' ->> 'df_value')::text AS type_of_case,
    (doc -> 'DFields' -> 'values' -> 'unique_id_of_case' ->> 'df_value')::text AS unique_id_of_case,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'given' ->> 'df_value')::text AS given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'sex' ->> 'df_value')::text AS sex,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'date_of_birth' ->> 'df_value')::text AS date_of_birth,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_years' ->> 'df_value')::text AS age_years,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_months' ->> 'df_value')::text AS age_months,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'country' ->> 'df_value')::text AS country,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'town_village_camp' ->> 'df_value')::text AS town_village_camp,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation' ->> 'df_value')::text AS occupation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation_other' ->> 'df_value')::text AS occupation_other,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_residence' ->> 'df_value')::text AS title_residence,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_parent_guradian' ->> 'df_value')::text AS title_parent_guardian,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_family_name' ->> 'df_value')::text AS guardian_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_given_name' ->> 'df_value')::text AS guardian_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_phone_number' ->> 'df_value')::text AS guardian_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_respondent' ->> 'df_value')::text AS title_respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS respondent_demographics,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_family_name' ->> 'df_value')::text AS respondent_family_name_demographics,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_given_name' ->> 'df_value')::text AS respondent_given_name_demographics,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_phone_number' ->> 'df_value')::text AS respondent_phone_number_demographics,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_relationship' ->> 'df_value')::text AS respondent_relationship_demographics,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_address' ->> 'df_value')::text AS respondent_address_demographics,
    (doc -> 'DForms' -> 'case_contact' -> 0 -> 'DFields' -> 'values' -> 'surname' ->> 'df_value')::text AS contact_surname,
    (doc -> 'DForms' -> 'case_contact' -> 0 -> 'DFields' -> 'values' -> 'given_name' ->> 'df_value')::text AS contact_given_name,
    (doc -> 'DForms' -> 'case_contact' -> 0 -> 'DFields' -> 'values' -> 'gender' ->> 'df_value')::text AS contact_gender,
    (doc -> 'DForms' -> 'case_contact' -> 0 -> 'DFields' -> 'values' -> 'age' ->> 'df_value')::text AS contact_age,
    (doc -> 'DForms' -> 'case_outcome' -> 0 -> 'DFields' -> 'values' -> 'final_case_classification' ->> 'df_value')::text AS outcome_final_case_classification,
    (doc -> 'DForms' -> 'case_outcome' -> 0 -> 'DFields' -> 'values' -> 'final_patient_status' ->> 'df_value')::text AS outcome_final_patient_status,
    (doc -> 'DForms' -> 'case_outcome' -> 0 -> 'DFields' -> 'values' -> 'final_patient_status_other' ->> 'df_value')::text AS outcome_final_patient_status_other,
    (doc -> 'DForms' -> 'case_outcome' -> 0 -> 'DFields' -> 'values' -> 'reason_for_referral' ->> 'df_value')::text AS outcome_reason_for_referral,
    (doc -> 'DForms' -> 'case_outcome' -> 0 -> 'DFields' -> 'values' -> 'date_of_outcome' ->> 'df_value')::text AS outcome_date_of_outcome,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'record_exposure' ->> 'df_value')::text AS exposure_record_exposure,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'exposure_type' ->> 'df_value')::text AS exposure_exposure_type,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_name' ->> 'df_value')::text AS exposure_food_name,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_consumption_date' ->> 'df_value')::text AS exposure_food_consumption_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_source' ->> 'df_value')::text AS exposure_food_source,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_participants_count' ->> 'df_value')::text AS exposure_food_participants_count,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_affected_participants_count' ->> 'df_value')::text AS exposure_food_affected_participants_count,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'water_sources' ->> 'df_value')::text AS exposure_water_sources,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'water_sources_other' ->> 'df_value')::text AS exposure_water_sources_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'toilet_types' ->> 'df_value')::text AS exposure_toilet_types,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'toilet_types_other' ->> 'df_value')::text AS exposure_toilet_types_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_origin_country' ->> 'df_value')::text AS exposure_travel_origin_country,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_origin_city' ->> 'df_value')::text AS exposure_travel_origin_city,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_departure_date' ->> 'df_value')::text AS exposure_travel_departure_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_destination_country' ->> 'df_value')::text AS exposure_travel_destination_country,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_destination_city' ->> 'df_value')::text AS exposure_travel_destination_city,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_arrival_date' ->> 'df_value')::text AS exposure_travel_arrival_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure' ->> 'df_value')::text AS exposure_animal_exposure,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_other' ->> 'df_value')::text AS exposure_animal_exposure_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_species' ->> 'df_value')::text AS exposure_animal_species,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_species_other' ->> 'df_value')::text AS exposure_animal_species_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_location' ->> 'df_value')::text AS exposure_animal_exposure_location,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_date' ->> 'df_value')::text AS animal_exposure_date,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS respondent,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS respondent_family_name,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'given_name' ->> 'df_value')::text AS respondent_given_name,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS respondent_phone_number,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'address' ->> 'df_value')::text AS respondent_address,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'relationship' ->> 'df_value')::text AS respondent_relationship,
    (doc -> 'DForms' -> 'case_repondent' -> 0 -> 'DFields' -> 'values' -> 'relationship_other' ->> 'df_value')::text AS respondent_relationship_other,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'case_seen_at_facility' ->> 'df_value')::text AS case_seen_at_facility,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'date_first_seen_at_facility' ->> 'df_value')::text AS date_first_seen_at_facility,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'admitted' ->> 'df_value')::text AS admitted,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'health_facility_name' ->> 'df_value')::text AS health_facility_name,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'admission_date' ->> 'df_value')::text AS admission_date,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'inpatient_number' ->> 'df_value')::text AS inpatient_number,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'discharge_date' ->> 'df_value')::text AS discharge_date,
    (doc -> 'DForms' -> 'case_hospitalization' -> 0 -> 'DFields' -> 'values' -> 'patient_status' ->> 'df_value')::text AS patient_status,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'laboratory_sample_collected' ->> 'df_value')::text AS laboratory_sample_collected,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'laboratory_samples_collected' ->> 'df_value')::text AS laboratory_samples_collected,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'laboratory_samples_collected_others' ->> 'df_value')::text AS laboratory_samples_collected_others,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'sample_date' ->> 'df_value')::text AS sample_date,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'rdt_done' ->> 'df_value')::text AS rdt_done,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'rdt_results' ->> 'df_value')::text AS rdt_results,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'samples_sent_to_laboratory' ->> 'df_value')::text AS samples_sent_to_laboratory,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'laboratory_name' ->> 'df_value')::text AS laboratory_name,
    (doc -> 'DForms' -> 'case_lab_information' -> 0 -> 'DFields' -> 'values' -> 'sample_sent_to_lab_date' ->> 'df_value')::text AS sample_sent_to_lab_date,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms' ->> 'df_value')::text AS symptoms,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms_other' ->> 'df_value')::text AS symptoms_other,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms_unexplained_bleeding' ->> 'df_value')::text AS symptoms_unexplained_bleeding,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms_start_date' ->> 'df_value')::text AS symptoms_start_date,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'title_symptoms_start_location' ->> 'df_value')::text AS title_symptoms_start_location,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms_start_county' ->> 'df_value')::text AS symptoms_start_county,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'symptoms_start_subcounty' ->> 'df_value')::text AS symptoms_start_subcounty,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'City / Town / Village / Camp' ->> 'df_value')::text AS symptoms_start_city_town_village_camp,
    (doc -> 'DForms' -> 'clinical_information_vhf' -> 0 -> 'DFields' -> 'values' -> 'outcome' ->> 'df_value')::text AS outcome
FROM {{ source('couchdb', 'couchdb') }}
WHERE 
    (doc ->> 'type') = 'dform'
AND
    (doc -> 'DFields' -> 'values' -> 'syndrome' ->> 'df_value')::text = 'VHF'
AND
    (doc ->> 'ident') IS NOT NULL
