{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT
    case_unique_id,
    case_date,
    epi_week,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    sample_number,
    date_of_sample_collection,
    time_of_sample_collection,
    type_of_food_product,
    type_of_food_sample,
    name_of_product,
    description_of_product,
    batch_number,
    date_of_manufacture,
    date_of_expiry,
    name_of_manufacturer,
    name_of_importer_dealer,
    method_of_collection,
    size_of_lot_sample,
    specimen_seal_used,
    reason_for_collection,
    reason_for_collection_other,
    mode_of_sample_delivery,
    date_of_dispatch,
    time_of_dispatch,
    number_of_invoice,
    date_of_invoice,
    shipping_record,
    date_of_shipping,
    sample_collector_name,
    sample_collector_designation,
    collector_phone_number,
    collectors_email_address,
    title_site_information,
    county,
    subcounty,
    ward,
    landmark,
    type_of_premise,
    name_of_premise,
    premise_phone_number,
    premise_email_address
FROM {{ ref('int_food_drugs_and_chemicals_sampling_form') }}
