{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT
    mform_id,
    form_id,
    case_unique_id,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    type_of_case,
    unique_id_of_case,
    given_name,
    family_name,
    sex,
    age_years,
    age_months,
    age_group,
    date_of_birth,
    phone_number,
    occupation,
    occupation_other,
    country,
    county,
    subcounty,
    town_village_camp,
    landmark,
    title_residence,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    reporting_county,
    reporting_subcounty,
    reporting_health_facility,
    vaccine,
    vaccine_doses,
    vaccine_last_dose_date,
    vaccine_information_source,
    lumbar_puncture_date,
    lumbar_puncture_time,
    celebrospinal_fluid_appearance,
    inoculation_date,
    inoculation_time,
    sample_transport_medium,
    sample_transport_medium_others,
    laboratory_test_requested,
    reference_laboratory,
    patient_on_treatment,
    symptoms,
    date_of_onset,
    clinical_health_facility,
    date_first_seen_at_facility,
    admission_date,
    patient_status
FROM {{ ref('int_meningitis') }}
