{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT
    mform_id,
    case_unique_id,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    given_name,
    family_name,
    sex,
    null::date AS date_of_birth,
    age_years,
    age_months,
    age_group,
    country,
    county,
    subcounty,
    town_village_camp,
    phone_number,
    occupation,
    occupation_other,
    title_residence,
    landmark,
    title_parent_guradian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    record_exposure,
    exposure_type,
    food_name,
    food_consumption_date,
    food_source,
    food_participants_count,
    food_affected_participants_count,
    water_sources,
    water_sources_other,
    toilet_types,
    toilet_types_other,
    travel_origin_country,
    travel_origin_city,
    travel_departure_date,
    travel_destination_country,
    travel_destination_city,
    travel_arrival_date,
    animal_exposure,
    animal_exposure_other,
    animal_species,
    animal_species_other,
    animal_exposure_location,
    animal_exposure_date,
    type_of_care,
    health_facility_mfl_number,
    health_facility_name,
    date_of_admission,
    inpatient_number,
    outcome_of_patient,
    date_of_death,
    status_of_patient,
    date_of_discharge,    
    rdt_done,
    rdt_results,
    laboratory_name,
    date_of_sample_collection,
    were_samples_collected,
    laboratory_samples_collected,
    laboratory_samples_collected_others,
    vaccinated,
    vaccine_doses,
    vaccination_date,
    date_of_onset,
    symptoms,
    symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM
    {{ ref('int_diarrhoeal_disease') }}  as int_diarrhoeal_disease

UNION

SELECT
    mform_id,
    case_unique_id,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    given_name,
    family_name,
    sex,
    null::date AS date_of_birth,
    age_years,
    age_months,
    age_group,
    country,
    county,
    subcounty,
    town_village_camp,
    phone_number,
    occupation,
    occupation_other,
    title_residence,
    landmark,
    title_parent_guradian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    record_exposure,
    exposure_type,
    food_name,
    food_consumption_date,
    food_source,
    food_participants_count,
    food_affected_participants_count,
    water_sources,
    water_sources_other,
    toilet_types,
    toilet_types_other,
    travel_origin_country,
    travel_origin_city,
    travel_departure_date,
    travel_destination_country,
    travel_destination_city,
    travel_arrival_date,
    animal_exposure,
    animal_exposure_other,
    animal_species,
    animal_species_other,
    animal_exposure_location,
    null::text AS animal_exposure_date,
    null::text AS type_of_care,
    null::text AS health_facility_mfl_number,
    null::text AS health_facility_name,
    null::text AS date_of_admission,
    null::text AS inpatient_number,
    null::text AS outcome_of_patient,
    null::text AS date_of_death,
    null::text AS status_of_patient,
    null::text AS date_of_discharge,    
    null::text AS rdt_done,
    null::text AS rdt_results,
    null::text AS laboratory_name,
    null::text AS date_of_sample_collection,
    null::text AS were_samples_collected,
    null::text AS laboratory_samples_collected,
    null::text AS laboratory_samples_collected_others,
    null::text AS vaccinated,
    null::text AS vaccine_doses,
    null::text AS vaccination_date,
    date_of_onset,
    null::text AS symptoms,
    null::text AS symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM {{ ref('int_acute_flaccid_paralysis') }} AS int_acute_flaccid_paralysis

UNION

SELECT
    mform_id,
    case_unique_id,
    null::text AS syndrome,
    null::text AS disease,
    null::date AS case_date,
    null::text AS epi_week,
    null::text AS epid,
    null::text AS date_of_investigation,
    null::text AS given_name,
    null::text AS family_name,
    null::text AS sex,
    null::date AS date_of_birth,
    null::float AS age_years,
    null::float AS age_months,
    null::text AS age_group,
    null::text AS country,
    null::text AS county,
    subcounty::text AS subcounty,
    village::text AS town_village_camp,
    null::text AS phone_number,
    null::text AS occupation,
    null::text AS occupation_other,
    null::text AS title_residence,
    null::text AS landmark,
    null::text AS title_parent_guradian,
    null::text AS guardian_family_name,
    null::text AS guardian_given_name,
    null::text AS guardian_phone_number,
    null::text AS title_respondent,
    null::text AS respondent,
    null::text AS respondent_family_name,
    null::text AS respondent_given_name,
    null::text AS respondent_address,
    null::text AS respondent_phone_number,
    null::text AS respondent_relationship,
    null::text AS record_exposure,
    null::text AS exposure_type,
    null::text AS food_name,
    null::text AS food_consumption_date,
    null::text AS food_source,
    null::text AS food_participants_count,
    null::text AS food_affected_participants_count,
    null::text AS water_sources,
    null::text AS water_sources_other,
    null::text AS toilet_types,
    null::text AS toilet_types_other,
    null::text AS travel_origin_country,
    null::text AS travel_origin_city,
    null::text AS travel_departure_date,
    null::text AS travel_destination_country,
    null::text AS travel_destination_city,
    null::text AS travel_arrival_date,
    null::text AS animal_exposure,
    null::text AS animal_exposure_other,
    null::text AS animal_species,
    null::text AS animal_species_other,
    null::text AS animal_exposure_location,
    null::text AS animal_exposure_date,
    null::text AS type_of_care,
    null::text AS health_facility_mfl_number,
    null::text AS health_facility_name,
    null::text AS date_of_admission,
    null::text AS inpatient_number,
    null::text AS outcome_of_patient,
    null::text AS date_of_death,
    null::text AS status_of_patient,
    null::text AS date_of_discharge,    
    null::text AS rdt_done,
    null::text AS rdt_results,
    null::text AS laboratory_name,
    null::text AS date_of_sample_collection,
    null::text AS were_samples_collected,
    null::text AS laboratory_samples_collected,
    null::text AS laboratory_samples_collected_others,
    null::text AS vaccinated,
    null::text AS vaccine_doses,
    null::text AS vaccination_date,
    null::text AS date_of_onset,
    null::text AS symptoms,
    null::text AS symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM {{ ref('int_community_led_total_sanitation') }}

UNION

SELECT
    mform_id,
    case_unique_id,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    given_name,
    family_name,
    sex,
    null::date as date_of_birth,
    age_years,
    null::float AS age_months,
    age_group,
    country,
    county,
    subcounty,
    town_village_camp,
    phone_number,
    occupation,
    occupation_other,
    title_residence,
    landmark,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    null::text AS record_exposure,
    null::text AS exposure_type,
    null::text AS food_name,
    null::text AS food_consumption_date,
    null::text AS food_source,
    null::text AS food_participants_count,
    null::text AS food_affected_participants_count,
    null::text AS water_sources,
    null::text AS water_sources_other,
    null::text AS toilet_types,
    null::text AS toilet_types_other,
    origin_country::text AS travel_origin_country,
    origin_city_town_illage_camp::text AS travel_origin_city,
    date_of_departure::text AS travel_departure_date,
    destination_country::text AS travel_destination_country,
    destination_city_town_village_camp::text AS travel_destination_city,
    date_of_arrival::text AS travel_arrival_date,
    null::text AS animal_exposure,
    null::text AS animal_exposure_other,
    null::text AS animal_species,
    null::text AS animal_species_other,
    null::text AS animal_exposure_location,
    null::text AS animal_exposure_date,
    null::text AS type_of_care,
    null::text AS health_facility_mfl_number,
    null::text AS health_facility_name,
    null::text AS date_of_admission,
    null::text AS inpatient_number,
    outcome::text AS outcome_of_patient,
    date_of_death,
    status_of_patient,
    date_of_discharge,
    null::text AS rdt_done,
    null::text AS rdt_results,
    laboratory_facility_name::text AS laboratory_name,
    date_of_sample_collection,
    were_samples_collected,
    laboratory_samples_collected,
    null::text AS laboratory_samples_collected_others,
    vaccination_exists::text AS vaccinated,
    doses_of_vaccine::text AS vaccine_doses,
    date_of_vaccination::text AS vaccination_date,
    date_of_onset,
    symptoms,
    symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM {{ ref('int_measles') }}

UNION

SELECT
    mform_id,
    case_unique_id,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    given_name,
    family_name,
    sex,
    null::date as date_of_birth,
    age_years,
    null::float AS age_months,
    age_group,
    country,
    county,
    subcounty,
    town_village_camp,
    phone_number,
    occupation,
    occupation_other,
    title_residence,
    landmark,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    null::text AS record_exposure,
    null::text AS exposure_type,
    null::text AS food_name,
    null::text AS food_consumption_date,
    null::text AS food_source,
    null::text AS food_participants_count,
    null::text AS food_affected_participants_count,
    null::text AS water_sources,
    null::text AS water_sources_other,
    null::text AS toilet_types,
    null::text AS toilet_types_other,
    null::text AS travel_origin_country,
    null::text AS travel_origin_city,
    null::text AS travel_departure_date,
    null::text AS travel_destination_country,
    null::text AS travel_destination_city,
    null::text AS travel_arrival_date,
    null::text AS animal_exposure,
    null::text AS animal_exposure_other,
    null::text AS animal_species,
    null::text AS animal_species_other,
    null::text AS animal_exposure_location,
    null::text AS animal_exposure_date,
    null::text AS type_of_care,
    null::text AS health_facility_mfl_number,
    null::text AS health_facility_name,
    null::text AS date_of_admission,
    null::text AS inpatient_number,
    null::text AS outcome_of_patient,
    null::text AS date_of_death,
    null::text AS status_of_patient,
    null::text AS date_of_discharge,
    null::text AS rdt_done,
    null::text AS rdt_results,
    null::text AS laboratory_name,
    null::text AS date_of_sample_collection,
    null::text AS were_samples_collected,
    null::text AS laboratory_samples_collected,
    null::text AS laboratory_samples_collected_others,
    null::text AS vaccinated,
    null::text AS vaccine_doses,
    null::text AS vaccination_date,
    date_of_onset,
    symptoms,
    null::text AS symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM {{ ref('int_meningitis') }}

UNION

SELECT
    mform_id,
    case_unique_id,
    ''::text AS syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    given_name,
    family_name,
    sex,
    date_of_birth,
    age_years,
    age_months,
    age_group,
    country,
    county,
    subcounty,
    town_village_camp,
    phone_number,
    occupation,
    occupation_other,
    title_residence,
    landmark,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    null::text AS record_exposure,
    null::text AS exposure_type,
    null::text AS food_name,
    null::text AS food_consumption_date,
    null::text AS food_source,
    null::text AS food_participants_count,
    null::text AS food_affected_participants_count,
    null::text AS water_sources,
    null::text AS water_sources_other,
    null::text AS toilet_types,
    null::text AS toilet_types_other,
    null::text AS travel_origin_country,
    null::text AS travel_origin_city,
    null::text AS travel_departure_date,
    null::text AS travel_destination_country,
    null::text AS travel_destination_city,
    null::text AS travel_arrival_date,
    null::text AS animal_exposure,
    null::text AS animal_exposure_other,
    null::text AS animal_species,
    null::text AS animal_species_other,
    null::text AS animal_exposure_location,
    null::text AS animal_exposure_date,
    type_of_care,
    mfl_number_of_health_facility::text AS health_facility_mfl_number,
    name_of_health_facility::text AS health_facility_name,
    date_of_admission,
    inpatient_number,
    outcome_of_patient,
    date_of_death,
    status_of_patient,
    date_of_discharge,
    null::text AS rdt_done,
    null::text AS rdt_results,
    name_of_laboratory_facility::text AS laboratory_name,
    date_of_sample_collection,
    laboratory_samples_were_collected::text AS were_samples_collected,
    laboratory_samples_collected,
    null::text AS laboratory_samples_collected_others,
    null::text AS vaccinated,
    null::text AS vaccine_doses,
    null::text AS vaccination_date,
    null::text AS date_of_onset,
    null::text AS symptoms,
    null::text AS symptoms_other,
    location_accuracy,
    location_latitude,
    location_longitude,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    current_date AS load_date
FROM {{ ref('int_neonatal_tetanus') }}
