{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT
    mform_id,
    form_id,
    case_unique_id,
    case_date,
    epi_week,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    sample_number,
    date_of_sample_collection,
    time_of_sample_collection,
    reason_for_sampling,
    reason_for_sampling_other,
    source_of_sample,
    sample_supected_of_causing_illness,
    sample_source_has_pump,
    sample_source_pump_usage_duration,
    sample_source_pump_overhaul,
    sample_is_repeat,
    previous_sample_status,
    rejected_sample_tracking_number,
    sources_of_pollution_exist,
    type_of_pollution,
    description_of_pollution,
    water_sample_source_is_treated,
    water_sample_source_method_of_treatment,
    water_sample_source_date_of_treatment,
    sample_collector_name,
    sample_collector_designation,
    collector_phone_number,
    collectors_email_address,
    date_of_sample_reception,
    date_of_sample_examination,
    presumptive_coli_test,
    escherichia_coli,
    specialist_bacteriologist,
    compiled_by,
    reviewed_by,
    title_site_information,
    county,
    subcounty,
    ward,
    landmark,
    sample_collection_pickup_site
FROM {{ ref('int_water_sampling') }}