{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT
    mform_id,
    form_id,
    case_unique_id,
    case_date,
    epi_week,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    sources_of_water,
    sources_of_water_other,
    water_source_is_protected,
    water_source_is_treated,
    water_source_method_of_treatment,
    water_source_method_of_treatment_other,
    distance_of_water_source_from_household,
    amount_of_water_consumed,
    type_of_water_storage_container,
    type_of_water_storage_container_other,
    dedicated_storage_container_for_drinking_water,
    water_storage_is_covered,
    sample_collector_name,
    sample_collector_designation,
    collector_phone_number,
    collectors_email_address,
    handwashing_facility_exists,
    handwashing_facility_has_water_and_soap,
    handwashing_facility_near_water_source,
    household_sanitation_facilities,
    household_sanitation_facilities_other,
    household_sanitation_method_in_use,
    distance_of_sanitation_facility_from_water_source,
    stagnant_water_exists,
    sources_of_stagnant_water,
    challenges_due_to_stagnant_water,
    challenges_due_to_stagnant_water_other,
    drainage_slope_exists,
    method_of_solid_waste_disposal,
    method_of_solid_waste_disposal_other,
    title_site_information,
    county,
    subcounty,
    ward,
    town_village_camp,
    landmark,
    title_head_of_household,
    name_of_head_of_household,
    phone_number_of_head_of_household,
    email_of_head_of_household,
    title_population,
    population_of_household_under_five_years
FROM {{ ref('int_rapid_wash_assessment_tool') }}
