name: Deploy ADAM prod replica dbt

on:
  schedule:
    # - cron: '*/5 * * * *'

env:
  DBT_SERVER_PROD: ${{ secrets.DBT_SERVER_PROD }}
  DBT_PORT_PROD: ${{ secrets.DBT_PORT_PROD }}
  DBT_USER_PROD: ${{ secrets.DBT_USER_PROD }}
  DBT_PASSWORD_PROD: ${{ secrets.DBT_PASSWORD_PROD }}
  DBT_DATABASE_PROD: ${{ secrets.DBT_DATABASE_PROD }}
  DBT_SCHEMA_PROD: ${{ secrets.DBT_SCHEMA_PROD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          dbt deps --profiles-dir ./profiles/ --target prod

      - name: Run dbt seeds
        run: |
          dbt seed --profiles-dir ./profiles/ --target prod --full-refresh
          
      - name: Run dbt models
        run: |
          dbt run --profiles-dir ./profiles/ --target prod

      - name: Run dbt tests
        run: |
          dbt test --profiles-dir ./profiles/ --target prod

          
